import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.imageio.ImageReader;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import com.google.common.io.Files;

import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;

import java.awt.image.BufferedImage;

/**
 *
 * @author User
 */
public class Secondary extends javax.swing.JFrame {
	
	ImageIcon i = new ImageIcon("history\\tree0.png");
	String currentPath = "history\\tree0.png";

    /**
     * Creates new form Secondary
     */
    public Secondary() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color (190, 50, 52)); // color of frame
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // When you close the secondary window, the home window remains visible
        setLocationRelativeTo(null);  // centering frame
    }
    
    public int c = 1;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

    	jFileChooser = new javax.swing.JFileChooser();
        lbImage = new javax.swing.JLabel();
        lbTitle1 = new javax.swing.JLabel();
        lbTitle2 = new javax.swing.JLabel();
        lbTitle3 = new javax.swing.JLabel();
        btnSerch = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnSearch2 = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        open = new javax.swing.JMenuItem();
        save = new javax.swing.JMenuItem();
        jScrollPane = new javax.swing.JScrollPane();
        lbLegend = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbImage.setIcon(i); // NOI18N
        lbImage.setHorizontalAlignment(JLabel.CENTER);
        jScrollPane.setViewportView(lbImage);
        jScrollPane.getViewport().setBackground(new java.awt.Color (190, 50, 52));
        jScrollPane.setBorder(null);
        
        lbLegend.setIcon(new javax.swing.ImageIcon("legenda.png")); // NOI18N


        lbTitle1.setFont(new java.awt.Font("Castellar", 3, 14)); // NOI18N
        lbTitle1.setText("Here is his family tree! ");
        lbTitle1.setForeground(new Color(255, 255, 255));

        lbTitle2.setFont(new java.awt.Font("Castellar", 3, 14)); // NOI18N
        lbTitle2.setText("Choose the dynasty:");
        lbTitle2.setForeground(new Color(255, 255, 255));
        
        lbTitle3.setFont(new java.awt.Font("Castellar", 3, 14)); // NOI18N
        lbTitle3.setText("Search by name:");
        lbTitle3.setForeground(new Color(255, 255, 255));
        
        btnSerch.setText("Search");
        btnSerch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSerchActionPerformed(evt);
            }
        });
        
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        txtName.setForeground(new java.awt.Color(153, 153, 153));
        txtName.setText("Write a name...");
        txtName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNameMouseClicked(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
        });
        
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Augusto (Giulio Claudii,  27 a.C.-14 d.C.)", "Vespasiano (Flavii, 68-79)", "Adriano (Antonini, 117-138)", "Settimio_Severo (Severi, 193-211)", "Valeriano (Valeriani, 253-260)", "Costantino (Costantiniani, 306-337)" }));

        btnSearch2.setText("Search");
        btnSearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch2ActionPerformed(evt);
            }
        });
        
        jMenu.setText("File");

        open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        open.setText("Open history");
        open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActionPerformed(evt);
            }
        });
        jMenu.add(open);

        save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jMenu.add(save);

        jMenuBar.add(jMenu);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addComponent(lbTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 483, Short.MAX_VALUE)
                .addComponent(lbLegend)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(btnSearch2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSerch)
                .addGap(170, 170, 170))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(lbTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTitle3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(121, 121, 121))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lbTitle1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbLegend, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTitle2)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearch2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbTitle3)
                        .addGap(18, 18, 18)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSerch)))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>                        

    private void txtNameMouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        txtName.setText("");
        txtName.setForeground(new Color(0,0,0));
        /* When the user clicks on the text area,
        the writing is removed and the color is set to black
        */
    }                                    

    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {                                   
        // TODO add your handling code here:
    }     
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {                                   
        // TODO add your handling code here:
        int Answer = JOptionPane.showConfirmDialog(null, "Are you sure want to exit?", "Quit", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (Answer == JOptionPane.NO_OPTION) {
                setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            }
            if (Answer == JOptionPane.YES_OPTION) {
                System.exit(0);
            }
        /*
            When you click on the "x" it generates a confirmation message
            */
    }

    private void btnSerchActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        String input = txtName.getText();
        if (input.equals("Write a name...")){
        	JOptionPane.showMessageDialog(this, "Error! Enter valid input...", "Error", 0);
        }
        else {
	        int i = 0;
	        String link = "https://it.wikipedia.org/wiki/" + input;
	        
	        try {
	        	Person per = new Person(input, link);
	        	per.setCheckImperatore();
	        	if(per.checkImp()) {
	        		per.closeDriver(per.getDriver());
					Imperatore imp = new Imperatore(input, link, true);
					imp.setDinastia();
					imp.setPadre();
					imp.setMadre();
					imp.setConiuge();
					imp.setCheckImperatore();
					imp.setMandato();
					imp.setFigli();
					imp.closeDriver(imp.getDriver());
					System.out.println(imp.getNome());
					System.out.println("mandato:" + imp.getMandato());
					
					StringProcessor.processString(imp, "");
		        	TreeImage.setCodifica(StringProcessor.getCodifica());
		        	TreeImage.createImage(c);
		        	TreeImage.resetCodifica();
				}
				else {
					per.setDinastia();
					per.setPadre();
					per.setMadre();
					per.setConiuge();
					per.setFigli();
					per.closeDriver(per.getDriver());
					
					StringProcessor.processString(per, "");
		        	TreeImage.setCodifica(StringProcessor.getCodifica());
		        	TreeImage.createImage(c);
		        	TreeImage.resetCodifica();
		        	System.out.println(StringProcessor.getCodifica());
				}
	        }
	        catch (Exception e) {
	        	i = -1;
	        }
			
			
	        if (i == -1){
	            JOptionPane.showMessageDialog(this, "Attention! The page wikipedia"
	            		+ " not exist ...", "Attention", 2);
	        }
	        else{
	        	currentPath = "history\\tree" + c + ".png";
	        	lbImage.setIcon(new javax.swing.ImageIcon(currentPath));       	
	        	c++;
	        }
        }
    }       
    
    private void btnSearch2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	String input = (String) jComboBox1.getSelectedItem();
    	input = input.substring(0, input.indexOf(' '));
        int i = 0;
        String link = "https://it.wikipedia.org/wiki/" + input;
        
        try {
        	Person per = new Person(input, link);
        	per.setCheckImperatore();
        	if(per.checkImp()) {
        		per.closeDriver(per.getDriver());
				Imperatore imp = new Imperatore(input, link, true);
				imp.setDinastia();
				imp.setPadre();
				imp.setMadre();
				imp.setConiuge();
				imp.setCheckImperatore();
				imp.setMandato();
				imp.setFigli();
				imp.closeDriver(imp.getDriver());
				System.out.println(imp.getNome());
				System.out.println("mandato:" + imp.getMandato());
				
				StringProcessor.processString(imp, "");
	        	TreeImage.setCodifica(StringProcessor.getCodifica());
	        	TreeImage.createImage(c);
	        	TreeImage.resetCodifica();
			}
			else {
				per.setDinastia();
				per.setPadre();
				per.setMadre();
				per.setConiuge();
				per.setFigli();
				per.closeDriver(per.getDriver());
				
				StringProcessor.processString(per, "");
	        	TreeImage.setCodifica(StringProcessor.getCodifica());
	        	TreeImage.createImage(c);
	        	TreeImage.resetCodifica();
			}
        }
        catch (Exception e) {
        	i = -1;
        }
		
		
        if (i == -1){
            JOptionPane.showMessageDialog(this, "Attention! The page wikipedia"
            		+ " not exist ...", "Attention", 2);
        }
        else{
        	currentPath = "history\\tree" + c + ".png";
        	lbImage.setIcon(new javax.swing.ImageIcon(currentPath));       	
        	c++;
        }
    }     
    
    private void saveActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    	jFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
       	int response = jFileChooser.showOpenDialog(null);
        if (response == jFileChooser.APPROVE_OPTION){
            File f = new File(jFileChooser.getSelectedFile().getAbsolutePath() + "\\download" + c + ".png");
            File curr = new File(currentPath);
            try {
            	Files.copy(curr, f);    
            	JOptionPane.showMessageDialog(this, "Rescue successful!", "Success", 1);
            }
            catch (Exception e){
            	JOptionPane.showMessageDialog(this, "Attention! File not exist ...", "Attention", 2);
            }
        }
    	
    } 
    
    private void openActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    	try {
    		Desktop.getDesktop().open(new File("history"));
        } catch (IOException ex) {
        	JOptionPane.showMessageDialog(this, "Attention! Directory not exist ...", "Attention", 2);
        }
    } 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Secondary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Secondary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Secondary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Secondary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Secondary().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnSearch2;
    private javax.swing.JButton btnSerch;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JLabel lbImage;
    private javax.swing.JLabel lbTitle1;
    private javax.swing.JLabel lbTitle2;
    private javax.swing.JLabel lbTitle3;
    private javax.swing.JMenuItem open;
    private javax.swing.JMenuItem save;
    private javax.swing.JTextField txtName;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel lbLegend;
    // End of variables declaration                   
}
